name: sep_1
description: Septerional Sep-1 model.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  ml_algo: any
  csv: any
  ml_dataframe: any

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

assets:
  - assets/respiration/Sleep_health_and_lifestyle_dataset.csv
